=== Unisens/unisens4csharp/src/unisens.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.unisens.org/unisens2.0" xmlns="http://www.unisens.org/unisens2.0">
	<xs:element name="unisens">
		<xs:annotation>
			<xs:documentation>Unisens 2.0 root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name = "customAttributes" type="customAttributes" minOccurs="0" maxOccurs="1"/>
				<xs:element name="context" type="context" minOccurs="0"/>
				<xs:choice id="entries" maxOccurs="unbounded" minOccurs="0">
					<xs:element name="signalEntry" type="signalEntry"/>
					<xs:element name="valuesEntry" type="valuesEntry"/>
					<xs:element name="eventEntry" type="eventEntry"/>
					<xs:element name="customEntry" type="customEntry"/>
				</xs:choice>
				<xs:element name="group" type="group" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<xs:attribute name="measurementId" type="xs:string" use="required"/>
			<xs:attribute name="timestampStart" type="xs:dateTime" use="required"/>
			<xs:attribute name="duration" type="xs:duration" use="optional"/>
			<xs:attribute name="comment" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="customAttributes">
		<xs:sequence>
			<xs:element name="customAttribute" type="customAttribute" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="customAttribute">
		<xs:attribute name="key">
			<xs:annotation>
				<xs:documentation>
					Custom key for a custom attribute.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="value">
			<xs:annotation>
				<xs:documentation>
					Custom value for the corresponding key.
				</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	<xs:complexType name="fileFormat" abstract="true">
		<xs:attribute name="comment" type="xs:string">
			<xs:annotation>
				<xs:documentation>Free comment.</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xmlFileFormat">
		<xs:annotation>
			<xs:documentation>file format options for XML files</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fileFormat"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="csvFileFormat">
		<xs:annotation>
			<xs:documentation>file format options for CSV files</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fileFormat">
				<xs:attribute name="separator" type="xs:string">
					<xs:annotation>
						<xs:documentation>
							Separator inside CSV files, normally
							semicolon or comma.
						</xs:documentation>
					</xs:annotation></xs:attribute>
				<xs:attribute name="decimalSeparator" type="xs:string">
					<xs:annotation>
						<xs:documentation>
							Decimal seperator inside CSV file, usually a
							dot or a comma.
						</xs:documentation>
					</xs:annotation></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="binFileFormat">
		<xs:annotation>
			<xs:documentation>file format options for binary files</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fileFormat">
				<xs:attribute name="endianess" type ="Endianess">
					<xs:annotation>
						<xs:documentation>
							Byte order: LITTLE or BIG for little
							endianess or big endianess.
						</xs:documentation>
					</xs:annotation></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="customFileFormat">
		<xs:annotation>
			<xs:documentation>file format options for custom files</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="fileFormat">
				<xs:attribute name="fileFormatName" type ="xs:string"/>
				<xs:anyAttribute/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name="Endianess">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LITTLE"/>
			<xs:enumeration value="BIG"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="entry" abstract="true">
		<xs:sequence>
			<xs:element name = "customAttributes" type="customAttributes" minOccurs="0" maxOccurs="1"/>
			<xs:choice id="fileFormat" minOccurs="1" maxOccurs="1">
				<xs:element name="binFileFormat" type="binFileFormat"/>
				<xs:element name="csvFileFormat" type="csvFileFormat"/>
				<xs:element name="xmlFileFormat" type="xmlFileFormat"/>
				<xs:element name="customFileFormat" type="customFileFormat"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="unisensFilename" use="required">
			<xs:annotation>
				<xs:documentation>
					The identifier of an entry corresponds to the
					filename containing the data. The identifier is
					unique.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="contentClass" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					The content class describes the type of data. The
					content class should be choosen from a list of
					recommended content classes like ECG, ACC for
					acceleration signals, IMP for impedance, TRIGGER for
					trigger lists etc. The content class is in uppercase
					letters.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="source" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					The source describes the data origin of the data,
					for example the recorder's name.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="sourceId" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					The source identifier contains the serial number of
					the used recorder.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="comment" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					A free comment, can be used to describe this entry.
				</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="measurementEntry" abstract="true">
		<xs:complexContent>
			<xs:extension base="entry">
				<xs:sequence>
					<xs:element name="channel" type="channel" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="sampleRate" type="xs:double" use="required"/>
				<xs:attribute name="adcZero" type="xs:int" use="optional"/>
				<xs:attribute name="baseline" type="xs:int" use="optional"/>
				<xs:attribute name="lsbValue" type="xs:double" use="optional"/>
				<xs:attribute name="adcResolution" type="xs:int" use="optional"/>
				<xs:attribute name="dataType" type="DataType" use="optional"/>
				<xs:attribute name="unit" type="xs:string" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name="DataType">
        <xs:annotation>
        	<xs:documentation>
        		Describes the data type of the data entry. A double is a
        		64 bit floating point value, a float is a 32 floating
        		point value.
        	</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
			<xs:enumeration value="double"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="uint8"/>
			<xs:enumeration value="int8"/>
			<xs:enumeration value="uint16"/>
			<xs:enumeration value="int16"/>
			<xs:enumeration value="uint32"/>
			<xs:enumeration value="int32"/>
			<xs:enumeration value="uint64"/>
			<xs:enumeration value="int64"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="signalEntry">
		<xs:complexContent>
			<xs:extension base="measurementEntry"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="eventEntry">
		<xs:complexContent>
			<xs:extension base="entry">
				<xs:attribute name="sampleRate" type="xs:double" use="required">
					<xs:annotation>
						<xs:documentation>
							The sample rate is the used time base. A
							negative sample rate is for a fraction.
						</xs:documentation>
					</xs:annotation></xs:attribute>
				<xs:attribute name="commentLength" type="xs:int">
					<xs:annotation>
						<xs:documentation>
							Length of each comment.
						</xs:documentation>
					</xs:annotation></xs:attribute>
				<xs:attribute name="typeLength" type="xs:int">
					<xs:annotation>
						<xs:documentation>
							Length of each type.
						</xs:documentation>
					</xs:annotation></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="valuesEntry">
		<xs:complexContent>
			<xs:extension base="measurementEntry"/>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="customEntry">
		<xs:complexContent>
			<xs:extension base="entry">
				<xs:anyAttribute namespace="##any" processContents="lax"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="channel">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					The name of a channel
				</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	
	<xs:simpleType name="unisensFilename">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]|[a-z]|_|-|.){1,254}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="groupEntry">
		<xs:attribute name="ref" type="unisensFilename" use="required">
			<xs:annotation>
				<xs:documentation>
					ID of an entry inside this Unisens data set.
				</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="group">
		<xs:sequence>
			<xs:element name="groupEntry" type="groupEntry" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required">
			<xs:annotation>
				<xs:documentation>
					Identifier of this group, must be unique.
				</xs:documentation>
			</xs:annotation></xs:attribute>
		<xs:attribute name="comment" type="xs:string">
			<xs:annotation>
				<xs:documentation>A free comment.</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="context">
		<xs:attribute name="schemaUrl" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Contains the URL to the schema of the context XML
					file.
				</xs:documentation>
			</xs:annotation></xs:attribute>
	</xs:complexType>
	
</xs:schema>

=== Unisens/unisens4csharp/library-test/TestData/test_03/unisens.xml
<?xml version="1.0" encoding="UTF-8"?>
<unisens xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" xsi:schemaLocation="http://www.unisens.org/unisens2.0 http://www.unisens.org/unisens2.0/unisens.xsd">
   <signalEntry dataType="uint8" id="test_signal_1x12_UINT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint8" id="test_signal_2x12_UINT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="uint8" id="test_signal_1x1_UINT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint8" id="test_signal_2x1_UINT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int8" id="test_signal_1x12_INT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int8" id="test_signal_2x12_INT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int8" id="test_signal_1x1_INT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int8" id="test_signal_2x1_INT8.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="uint16" id="test_signal_1x12_UINT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint16" id="test_signal_2x12_UINT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="uint16" id="test_signal_1x1_UINT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint16" id="test_signal_2x1_UINT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int16" id="test_signal_1x12_INT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int16" id="test_signal_2x12_INT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int16" id="test_signal_1x1_INT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int16" id="test_signal_2x1_INT16.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="uint32" id="test_signal_1x12_UINT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint32" id="test_signal_2x12_UINT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="uint32" id="test_signal_1x1_UINT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="uint32" id="test_signal_2x1_UINT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int32" id="test_signal_1x12_INT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int32" id="test_signal_2x12_INT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
   <signalEntry dataType="int32" id="test_signal_1x1_INT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
   </signalEntry>
   <signalEntry dataType="int32" id="test_signal_2x1_INT32.bin" lsbValue="1" sampleRate="100">
      <binFileFormat endianess="BIG"/>
      <channel name="CH1"/>
      <channel name="CH2"/>
   </signalEntry>
</unisens>
